### ISSUE TITLE
Compatibily with Laravel 10

### ISSUE THREAD

**Issue by Deca** [Laravel-Backpack/NewsCRUD#67] opened 2023-02-19 23:14 UTC
# Bug report

### What I did:
Tried to install NewsCRUD with method A but gettin an error during migration (step 4)

### What I expected to happen:
Complete the migration

### What happened:
getting this error: 
``` 
 Illuminate\Contracts\Container\BindingResolutionException 
  Target class [Admin\ArticleCrudController] does not exist.
  at vendor\laravel\framework\src\Illuminate\Container\Container.php:891
  ```

### What I've already tried to fix it:
Testing on a fresh Laravel and Backpack install

### Backpack, Laravel, PHP, DB version:
Backpack 5.5, Laravel 10.0.3 , PHP 8.3, Mysql 5.7.24

**Comment by Deca** [comment] 2023-02-20 09:03
In addition Tested on another fresh installation but with Laravel 8.83 and backpack 5.5, I can go past the migration and finish all the step (A) but when when I try to open the /admin/article route i get a
``` Route [login] not defined. ```

Tried also to install as a package but can't get past
```composer require backpack/newscrud```  
![image](https://user-images.githubusercontent.com/3716783/220060436-b8ff4394-cf0f-40b8-9ca6-f9b5b0a84d37.png)
Should I try with a previous backpack release?

**Comment by pxpm** [comment] 2023-02-20 15:52
Hello @Deca 

From what I could check we already made this package L10 compatible here: https://github.com/Laravel-Backpack/NewsCRUD/pull/66

From the error it seems composer is not able to install `backpack/pro` that is a dependency of this addon. Do you have access to pro? If you do, do, please do a `php artisan backpack:require:pro`, this will automatically add the `repositories` entry in your `composer.json`, otherwise you can add the repository and setup the auth manually. 

After you should be able to install this package without issues. 

Going to close this, I don't think there is any L10 incompatibility here, please feel free to continue the conversation or re-open if needed.

Cheers

**Closed by pxpm** 2023-02-20 15:52 UTC

**Comment by Deca** [comment] 2023-02-21 18:27
Sorry to reopen the issue but maybe you overlook the first part of my second reply, were I was stating that I get an error on a fresh install Laravel 8.83 and backpack 5.5 using the method (A)
The only change I've made is to enable back the  automatic namespace prefixing (without it, wasn't anyway able to find the class [Admin\ArticleCrudController] ) and when I try to open articles, categories or tags I get a ````Route [login] not defined.```
I eve tried another fresh installation on a completely different env (ubuntu 20) but ending with the same error.
What I've not tried is to rollback to a previous backpack version

**Comment by pxpm** [comment] 2023-02-22 18:07
@Deca no problem in continuing the conversation, if there is an issue and I overlooked let's try to figure it out. 

I might got mislead-ed by the issue title `compatibility with Laravel 10`, sorry for that. 

Anyway, from your second screenshoot, in the issue you mentioned Laravel8, the error reported by composer is that PRO was not able to install, like I had already stated, so that may be the cause for the installation not properly finishing. 

If you want to use NewsCrud without PRO you need to use Backpack 4.1. 

Let me know if I am still missing something.

Cheers

**Comment by Deca** [comment] 2023-02-23 10:19
@pxpm Thanks for the reply, thats clear things out. 
But the documentation state that I should able to use it without pro with the manual install (A), is that limitation just introduced with the v5?
